version: '3.8'

services:
  app:
    build: .
    container_name: bookstore_app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: bookstore_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    ports:
      - "3307:3306"
